version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack/data
      - LS_TMP_DIR=/var/lib/localstack/tmp
    volumes:
      - localstack_data:/var/lib/localstack
      - ./scripts:/etc/localstack/init/ready.d  # <-- scripts run automatically


volumes:
  localstack_data:
